title: Brian Vander Plaats
description: Website
author: Brian Vander Plaats
logo: http://brianvp.github.io/static/img/avatar.png
github: https://github.com/brianvp
about: Developer
disqus_shortname: 
google_analytics: 
urls:
    - text: Home
      url: /
      icon: fa-home
      layout: post
    - text: About
      url: /about-me.html
      icon: fa-comments
    - text: Github
      url: https://github.com/brianvp
      icon: fa-github
    - text: XML Feed
      url: /feed.xml
      icon: fa-feed
    - text: Archive
      url: /archive
      icon: fa-folder
    - text: Categories
      url: /categories
      icon: fa-folder
    - text: Tags
      url: /categories
      icon: fa-folder
      
social:
    - icon: fa-facebook
      link: 'https://www.facebook.com/brianvanderplaats'
    - icon: fa-twitter
      link: 'https://twitter.com/Brianfromplace'
    - icon: fa-linkedin
      link: 'https://www.linkedin.com/pub/brian-vander-plaats/94/423/802'
    - icon: fa-stack-exchange
      link: 'http://stackoverflow.com/users/24892/brian-vander-plaats'

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

url: "http://brianvp.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist